### PR TITLE
DEP Dependencies for CMS 6

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/.github/issues/191

### CODE REVIEW

**Review by GuySartorelli — DISMISSED** [review]
LGTM. Failures are expected at this stage so ignoring CI.

**Comment by GuySartorelli** [comment]
Lets just ditch this one actually. There's NO WAY we're supporting this for CMS 6.

**Comment by emteknetnz** [comment]
We'll create a CMS 6 branch for now and look at support at a later date

**Review by GuySartorelli — APPROVED** [review]
It is absolutely insane that we're pretending we're gonna make this CMS 6 compatible....

**Pull request merged**
