### PR TITLE
Add bootstrap classes to FileWarningHeader

### LINKED ISSUE #12: UX Warning message needs bootstrap classes
The below warning message in the CMS is not easily distinguishable from the other text and perhaps needs some styling:

 image

### PR DESCRIPTION
**Pull request by raissanorth**
Added bootstrap classes to make the warning stand out more. Fixes #12 

**Note:** I am not able to set up this module locally, so I haven't tested if it actually renders correctly. Do you mind doing that @NightJar, pretty please?

### CODE REVIEW

**Review by robbieaverill — CHANGES_REQUESTED** [review]
If we are adding new HTML then I think the header field should be swapped for a LiteralField instead

**Comment by robbieaverill** [comment]
The changes look good, but whenever I add the `SilverStripe\DocumentConverter\PageExtension` class to `Page` I get redirected back to admin/pages whenever I click on a page in the CMS (context: CWP 2.0)

@NightJar would you mind taking a look at this PR and give it a quick test, if you've still got docvert running?

**Comment by robbieaverill** [comment]
Also @raissanorth you'll need to update the failing unit test :)

**Comment by NightJar** [comment]
L.G.T.M.
image
Mergy?

**Review by robbieaverill — APPROVED** [review]

**Pull request merged**
